
:toc:               left
:toc-title:         Connector Summary
:toclevels:         2
:last-update-label!:
:docinfo:
:source-highlighter: coderay
:icons: font


= Git Connector API Reference


*Additional Info*
[width="50", cols=".<60%,^40%" ]
|======================
| Requires Mule Enterprise License |  No icon:remove[]  {nbsp}
| Requires Entitlement |  No icon:remove[]  {nbsp}
| Mule Version | 3.5.0 or higher
|======================


== Configs
---
=== Git Configuration
`<git:config>`


`Connection Management` 



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
| Name | Java Type | Description | Default Value | Required
|name | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | The name of this configuration. With this name can be later referenced. | | *x*{nbsp}
| username | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++A username+++ |   | *x*{nbsp}
| password | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++A password+++ |   | *x*{nbsp}
| directory | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Default repository base directory+++ |   | {nbsp}
|======================



== Processors

---

=== Clone repository
`<git:clone-repository>`




+++
Clone a repository into a new directory or resset it if it exists
../../../doc/mule-module-git.xml.sample git:clone
+++


    
                    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
uri  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The (possibly remote) repository to clone from.+++ |  | *x*{nbsp}




| 
bare  | +++boolean+++ | +++True if you want a bare Git repository, false otherwise.+++ | false | {nbsp}




| 
remote  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Name of the remote to keep track of the upstream repository.+++ | origin | {nbsp}




| 
branch  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Name of the local branch into which the remote will be cloned.+++ | HEAD | {nbsp}




| 
overrideDirectory  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Name of the directory to use for git repository+++ |  | {nbsp}


|======================





---

=== Reset repository
`<git:reset-repository>`






    
        
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
branch  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | ++++++ | HEAD | {nbsp}




| 
overrideDirectory  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | ++++++ |  | {nbsp}


|======================





---

=== Add
`<git:add>`




+++
Add file contents to the index
../../../doc/mule-module-git.xml.sample git:add
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
filePatterns  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++List of file patterns to add content from. Also a leading directory name (e.g. dir to add dir/file1 and dir/file2) can be given to add all files in the directory, recursively. Use semicolon (";") to separete patterns+++ |  | {nbsp}




| 
forceAll  | +++boolean+++ | +++Add all files+++ | false | {nbsp}




| 
overrideDirectory  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Name of the directory to use for git repository+++ |  | {nbsp}


|======================





---

=== Create branch
`<git:create-branch>`




+++
Create a local branch
../../../doc/mule-module-git.xml.sample git:create-branch
+++


    
                
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
branchName  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Name of the new branch+++ |  | *x*{nbsp}




| 
force  | +++boolean+++ | +++If true and the branch with the given name already exists, the start-point of an existing branch will be set to a new start-point; if false, the existing branch will not be changed.+++ | false | {nbsp}




| 
startPoint  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The new branch head will point to this commit. It may be given as a branch name, a commit-id, or a tag. If this option is omitted, the current HEAD will be used instead.+++ | HEAD | {nbsp}




| 
overrideDirectory  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Name of the directory to use for git repository+++ |  | {nbsp}


|======================





---

=== Delete branch
`<git:delete-branch>`




+++
Delete local branch
../../../doc/mule-module-git.xml.sample git:delete-branch
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
branchName  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Name of the branch to delete+++ |  | *x*{nbsp}




| 
force  | +++boolean+++ | +++If false a check will be performed whether the branch to be deleted is already merged into the current branch and deletion will be refused in this case+++ |  | *x*{nbsp}




| 
overrideDirectory  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Name of the directory to use for git repository+++ |  | {nbsp}


|======================





---

=== Commit
`<git:commit>`




+++
Record changes to the repository
../../../doc/mule-module-git.xml.sample git:commit
+++


    
                            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
msg  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Commit message+++ |  | *x*{nbsp}




| 
committerName  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Name of the person performing this commit+++ |  | *x*{nbsp}




| 
committerEmail  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Email of the person performing this commit+++ |  | *x*{nbsp}




| 
authorName  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Name of the author of the changes to commit+++ |  | {nbsp}




| 
authorEmail  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Email of the author of the changes to commit+++ |  | {nbsp}




| 
all  | +++boolean+++ | +++If set to true the Commit command automatically stages files that have been modified and deleted, but new files not known by the repository are not affected.+++ | false | {nbsp}




| 
overrideDirectory  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Name of the directory to use for git repository+++ |  | {nbsp}


|======================





---

=== Push
`<git:push>`




+++
Update remote refs along with associated objects
../../../doc/mule-module-git.xml.sample git:push
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
remote  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The remote (uri or name) used for the push operation.+++ | origin | {nbsp}




| 
force  | +++boolean+++ | +++Sets the force preference for push operation+++ | false | {nbsp}




| 
overrideDirectory  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Name of the directory to use for git repository+++ |  | {nbsp}


|======================





---

=== Pull
`<git:pull>`




+++
Fetch from and merge with another repository or a local branch
../../../doc/mule-module-git.xml.sample git:pull
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
overrideDirectory  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Name of the directory to use for git repository+++ |  | {nbsp}


|======================





---

=== Fetch
`<git:fetch>`




+++
Fetch changes from another repository
../../../doc/mule-module-git.xml.sample git:fetch
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
overrideDirectory  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Name of the directory to use for git repository+++ |  | {nbsp}


|======================





---

=== Checkout
`<git:checkout>`




+++
Checkout a local branch or create a local branch from a remote branch
../../../doc/mule-module-git.xml.sample git:checkout
or
../../../doc/mule-module-git.xml.sample git:checkout
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
branch  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Name of the branch to checkout+++ |  | *x*{nbsp}




| 
startPoint  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++If specified creates a new branch pointing to this startPoint+++ |  | {nbsp}




| 
overrideDirectory  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Name of the directory to use for git repository+++ |  | {nbsp}


|======================















