var DATA = [
      { id:0, label:"add", link:"mule/git.html#add", type:"method" },
      { id:1, label:"checkout", link:"mule/git.html#checkout", type:"method" },
      { id:2, label:"clone", link:"mule/git.html#clone", type:"method" },
      { id:3, label:"commit", link:"mule/git.html#commit", type:"method" },
      { id:4, label:"create-branch", link:"mule/git.html#create-branch", type:"method" },
      { id:5, label:"delete-branch", link:"mule/git.html#delete-branch", type:"method" },
      { id:6, label:"fetch", link:"mule/git.html#fetch", type:"method" },
      { id:7, label:"org.mule.module.git", link:"java/org/mule/module/git/package-summary.html", type:"package" },
      { id:8, label:"org.mule.module.git.GitConnector", link:"java/org/mule/module/git/GitConnector.html", type:"class" },
      { id:9, label:"org.mule.module.git.config", link:"java/org/mule/module/git/config/package-summary.html", type:"package" },
      { id:10, label:"org.mule.module.git.config.AddMessageProcessor", link:"java/org/mule/module/git/config/AddMessageProcessor.html", type:"class" },
      { id:11, label:"org.mule.module.git.config.CheckoutMessageProcessor", link:"java/org/mule/module/git/config/CheckoutMessageProcessor.html", type:"class" },
      { id:12, label:"org.mule.module.git.config.CloneRepositoryMessageProcessor", link:"java/org/mule/module/git/config/CloneRepositoryMessageProcessor.html", type:"class" },
      { id:13, label:"org.mule.module.git.config.CommitMessageProcessor", link:"java/org/mule/module/git/config/CommitMessageProcessor.html", type:"class" },
      { id:14, label:"org.mule.module.git.config.CreateBranchMessageProcessor", link:"java/org/mule/module/git/config/CreateBranchMessageProcessor.html", type:"class" },
      { id:15, label:"org.mule.module.git.config.DeleteBranchMessageProcessor", link:"java/org/mule/module/git/config/DeleteBranchMessageProcessor.html", type:"class" },
      { id:16, label:"org.mule.module.git.config.FetchMessageProcessor", link:"java/org/mule/module/git/config/FetchMessageProcessor.html", type:"class" },
      { id:17, label:"org.mule.module.git.config.GitConnectorCapabilitiesAdapter", link:"java/org/mule/module/git/config/GitConnectorCapabilitiesAdapter.html", type:"class" },
      { id:18, label:"org.mule.module.git.config.GitConnectorLifecycleAdapter", link:"java/org/mule/module/git/config/GitConnectorLifecycleAdapter.html", type:"class" },
      { id:19, label:"org.mule.module.git.config.PullMessageProcessor", link:"java/org/mule/module/git/config/PullMessageProcessor.html", type:"class" },
      { id:20, label:"org.mule.module.git.config.PushMessageProcessor", link:"java/org/mule/module/git/config/PushMessageProcessor.html", type:"class" },
      { id:21, label:"org.mule.module.git.config.spring", link:"java/org/mule/module/git/config/spring/package-summary.html", type:"package" },
      { id:22, label:"org.mule.module.git.config.spring.AddDefinitionParser", link:"java/org/mule/module/git/config/spring/AddDefinitionParser.html", type:"class" },
      { id:23, label:"org.mule.module.git.config.spring.CheckoutDefinitionParser", link:"java/org/mule/module/git/config/spring/CheckoutDefinitionParser.html", type:"class" },
      { id:24, label:"org.mule.module.git.config.spring.CloneRepositoryDefinitionParser", link:"java/org/mule/module/git/config/spring/CloneRepositoryDefinitionParser.html", type:"class" },
      { id:25, label:"org.mule.module.git.config.spring.CommitDefinitionParser", link:"java/org/mule/module/git/config/spring/CommitDefinitionParser.html", type:"class" },
      { id:26, label:"org.mule.module.git.config.spring.CreateBranchDefinitionParser", link:"java/org/mule/module/git/config/spring/CreateBranchDefinitionParser.html", type:"class" },
      { id:27, label:"org.mule.module.git.config.spring.DeleteBranchDefinitionParser", link:"java/org/mule/module/git/config/spring/DeleteBranchDefinitionParser.html", type:"class" },
      { id:28, label:"org.mule.module.git.config.spring.FetchDefinitionParser", link:"java/org/mule/module/git/config/spring/FetchDefinitionParser.html", type:"class" },
      { id:29, label:"org.mule.module.git.config.spring.GitConnectorConfigDefinitionParser", link:"java/org/mule/module/git/config/spring/GitConnectorConfigDefinitionParser.html", type:"class" },
      { id:30, label:"org.mule.module.git.config.spring.GitConnectorNamespaceHandler", link:"java/org/mule/module/git/config/spring/GitConnectorNamespaceHandler.html", type:"class" },
      { id:31, label:"org.mule.module.git.config.spring.PullDefinitionParser", link:"java/org/mule/module/git/config/spring/PullDefinitionParser.html", type:"class" },
      { id:32, label:"org.mule.module.git.config.spring.PushDefinitionParser", link:"java/org/mule/module/git/config/spring/PushDefinitionParser.html", type:"class" },
      { id:33, label:"pull", link:"mule/git.html#pull", type:"method" },
      { id:34, label:"push", link:"mule/git.html#push", type:"method" }

    ];
